import type {
  Participant,
  Team,
  Project,
  Announcement,
  Judge,
  Evaluation,
  TimelineEvent,
  CheckInRecord,
} from './types';

const AVATAR_COLORS = [
  'from-brand-500 to-brand-400',
  'from-violet-500 to-violet-400',
  'from-emerald-500 to-emerald-400',
  'from-amber-500 to-amber-400',
  'from-rose-500 to-rose-400',
  'from-cyan-500 to-cyan-400',
  'from-fuchsia-500 to-fuchsia-400',
  'from-teal-500 to-teal-400',
];

const COLLEGES = [
  'IIT Bombay',
  'IIT Delhi',
  'IIT Madras',
  'BITS Pilani',
  'NIT Trichy',
  'VIT Vellore',
  'IIIT Hyderabad',
  'Delhi Technological University',
  'Anna University',
  'SRM Institute of Technology',
];

export const EVENT_INFO = {
  name: 'HackSphere 2026',
  tagline: 'Build. Break. Innovate.',
  venue: 'Convention Centre, IIT Bombay',
  startDate: '2026-09-19T09:00:00',
  endDate: '2026-09-21T18:00:00',
  organizer: 'EventSphere Operations',
};

export const initialParticipants: Participant[] = [
  {
    id: 'p1',
    regId: 'ES26-0001',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@iitb.ac.in',
    college: 'IIT Bombay',
    skills: ['React', 'TypeScript', 'Node.js', 'GraphQL'],
    role: 'Fullstack',
    teamStatus: 'in_team',
    teamId: 't1',
    checkedIn: true,
    checkedInAt: '2026-09-19T09:12:00',
    registeredAt: '2026-09-02T10:00:00',
    avatarColor: AVATAR_COLORS[0],
    projectInterests: ['AI Assistants', 'Developer Tools'],
    availability: 'Full weekend',
    matchScore: 96,
    bio: 'Fullstack builder, shipped 3 hackathon winners. Loves realtime systems.',
  },
  {
    id: 'p2',
    regId: 'ES26-0002',
    name: 'Diya Patel',
    email: 'diya.patel@bits.ac.in',
    college: 'BITS Pilani',
    skills: ['Figma', 'React', 'Next.js'],
    role: 'Designer',
    teamStatus: 'in_team',
    teamId: 't1',
    checkedIn: true,
    checkedInAt: '2026-09-19T09:20:00',
    registeredAt: '2026-09-03T11:00:00',
    avatarColor: AVATAR_COLORS[1],
    projectInterests: ['Healthcare', 'Education'],
    availability: 'Full weekend',
    matchScore: 92,
    bio: 'Product designer obsessed with micro-interactions and accessibility.',
  },
  {
    id: 'p3',
    regId: 'ES26-0003',
    name: 'Arjun Nair',
    email: 'arjun.nair@vit.ac.in',
    college: 'VIT Vellore',
    skills: ['Python', 'TensorFlow', 'PyTorch'],
    role: 'ML/AI',
    teamStatus: 'in_team',
    teamId: 't2',
    checkedIn: true,
    checkedInAt: '2026-09-19T09:05:00',
    registeredAt: '2026-09-01T09:00:00',
    avatarColor: AVATAR_COLORS[2],
    projectInterests: ['AI Assistants', 'Healthcare'],
    availability: 'Full weekend',
    matchScore: 94,
    bio: 'ML researcher, 2 papers on efficient inference. Kaggle Expert.',
  },
  {
    id: 'p4',
    regId: 'ES26-0004',
    name: 'Ishita Reddy',
    email: 'ishita.reddy@iiit.ac.in',
    college: 'IIIT Hyderabad',
    skills: ['Python', 'TensorFlow', 'Go'],
    role: 'ML/AI',
    teamStatus: 'in_team',
    teamId: 't2',
    checkedIn: true,
    checkedInAt: '2026-09-19T09:30:00',
    registeredAt: '2026-09-04T12:00:00',
    avatarColor: AVATAR_COLORS[3],
    projectInterests: ['AI Assistants', 'Climate Tech'],
    availability: 'Full weekend',
    matchScore: 90,
    bio: 'Building edge ML pipelines. Loves distributed systems.',
  },
  {
    id: 'p5',
    regId: 'ES26-0005',
    name: 'Kabir Singh',
    email: 'kabir.singh@iitd.ac.in',
    college: 'IIT Delhi',
    skills: ['Solidity', 'React', 'Node.js'],
    role: 'Fullstack',
    teamStatus: 'in_team',
    teamId: 't3',
    checkedIn: true,
    checkedInAt: '2026-09-19T09:45:00',
    registeredAt: '2026-09-05T14:00:00',
    avatarColor: AVATAR_COLORS[4],
    projectInterests: ['Web3', 'Fintech'],
    availability: 'Full weekend',
    matchScore: 88,
    bio: 'Web3 builder, smart contract auditor. ETHGlobal finalist.',
  },
  {
    id: 'p6',
    regId: 'ES26-0006',
    name: 'Ananya Iyer',
    email: 'ananya.iyer@nit.edu',
    college: 'NIT Trichy',
    skills: ['React', 'TypeScript', 'Flutter'],
    role: 'Frontend',
    teamStatus: 'in_team',
    teamId: 't3',
    checkedIn: false,
    checkedInAt: null,
    registeredAt: '2026-09-06T15:00:00',
    avatarColor: AVATAR_COLORS[5],
    projectInterests: ['Gaming', 'Education'],
    availability: 'Saturday only',
    matchScore: 85,
    bio: 'Frontend specialist crafting delightful mobile-first experiences.',
  },
  {
    id: 'p7',
    regId: 'ES26-0007',
    name: 'Vivaan Gupta',
    email: 'vivaan.gupta@dtu.ac.in',
    college: 'Delhi Technological University',
    skills: ['Go', 'Docker', 'Kubernetes', 'AWS'],
    role: 'DevOps',
    teamStatus: 'in_team',
    teamId: 't4',
    checkedIn: true,
    checkedInAt: '2026-09-19T10:00:00',
    registeredAt: '2026-09-07T09:30:00',
    avatarColor: AVATAR_COLORS[6],
    projectInterests: ['Developer Tools', 'Climate Tech'],
    availability: 'Full weekend',
    matchScore: 91,
    bio: 'Platform engineer. Can spin up a k8s cluster in 4 minutes flat.',
  },
  {
    id: 'p8',
    regId: 'ES26-0008',
    name: 'Saanvi Rao',
    email: 'saanvi.rao@annauniv.edu',
    college: 'Anna University',
    skills: ['Figma', 'React', 'Next.js'],
    role: 'Designer',
    teamStatus: 'in_team',
    teamId: 't4',
    checkedIn: true,
    checkedInAt: '2026-09-19T10:10:00',
    registeredAt: '2026-09-08T10:00:00',
    avatarColor: AVATAR_COLORS[7],
    projectInterests: ['Healthcare', 'Education'],
    availability: 'Full weekend',
    matchScore: 87,
    bio: 'Design systems nerd. Previously at a healthtech startup.',
  },
  {
    id: 'p9',
    regId: 'ES26-0009',
    name: 'Reyansh Mehta',
    email: 'reyansh.mehta@srmist.edu.in',
    college: 'SRM Institute of Technology',
    skills: ['Python', 'PyTorch', 'TensorFlow'],
    role: 'ML/AI',
    teamStatus: 'in_team',
    teamId: 't5',
    checkedIn: true,
    checkedInAt: '2026-09-19T10:25:00',
    registeredAt: '2026-09-09T11:00:00',
    avatarColor: AVATAR_COLORS[0],
    projectInterests: ['AI Assistants', 'Healthcare'],
    availability: 'Full weekend',
    matchScore: 89,
    bio: 'NLP enthusiast. Building LLM agents for fun and profit.',
  },
  {
    id: 'p10',
    regId: 'ES26-0010',
    name: 'Myra Krishnan',
    email: 'myra.krishnan@iitm.ac.in',
    college: 'IIT Madras',
    skills: ['Rust', 'Go', 'PostgreSQL'],
    role: 'Backend',
    teamStatus: 'in_team',
    teamId: 't5',
    checkedIn: false,
    checkedInAt: null,
    registeredAt: '2026-09-10T12:00:00',
    avatarColor: AVATAR_COLORS[1],
    projectInterests: ['Developer Tools', 'Fintech'],
    availability: 'Full weekend',
    matchScore: 93,
    bio: 'Systems engineer. Believes Rust is the future of backend.',
  },
  {
    id: 'p11',
    regId: 'ES26-0011',
    name: 'Ayaan Verma',
    email: 'ayaan.verma@iitb.ac.in',
    college: 'IIT Bombay',
    skills: ['React', 'TypeScript', 'Node.js'],
    role: 'Fullstack',
    teamStatus: 'looking',
    teamId: null,
    checkedIn: true,
    checkedInAt: '2026-09-19T10:40:00',
    registeredAt: '2026-09-11T13:00:00',
    avatarColor: AVATAR_COLORS[2],
    projectInterests: ['Developer Tools', 'Gaming'],
    availability: 'Full weekend',
    matchScore: 84,
    bio: 'Solo hacker looking for a designer + ML teammate. 5 hackathons done.',
  },
  {
    id: 'p12',
    regId: 'ES26-0012',
    name: 'Kiara Bose',
    email: 'kiara.bose@bits.ac.in',
    college: 'BITS Pilani',
    skills: ['Figma', 'Next.js'],
    role: 'Designer',
    teamStatus: 'looking',
    teamId: null,
    checkedIn: true,
    checkedInAt: '2026-09-19T10:55:00',
    registeredAt: '2026-09-12T14:00:00',
    avatarColor: AVATAR_COLORS[3],
    projectInterests: ['Education', 'Healthcare'],
    availability: 'Full weekend',
    matchScore: 81,
    bio: 'Designer who codes. Seeking a backend-heavy team.',
  },
  {
    id: 'p13',
    regId: 'ES26-0013',
    name: 'Vihaan Joshi',
    email: 'vihaan.joshi@vit.ac.in',
    college: 'VIT Vellore',
    skills: ['Flutter', 'Dart', 'Firebase'],
    role: 'Mobile',
    teamStatus: 'looking',
    teamId: null,
    checkedIn: false,
    checkedInAt: null,
    registeredAt: '2026-09-13T15:00:00',
    avatarColor: AVATAR_COLORS[4],
    projectInterests: ['Gaming', 'Education'],
    availability: 'Saturday only',
    matchScore: 78,
    bio: 'Mobile dev. Want to build something kids actually use.',
  },
  {
    id: 'p14',
    regId: 'ES26-0014',
    name: 'Anika Pillai',
    email: 'anika.pillai@iiit.ac.in',
    college: 'IIIT Hyderabad',
    skills: ['Python', 'PyTorch', 'TensorFlow'],
    role: 'ML/AI',
    teamStatus: 'looking',
    teamId: null,
    checkedIn: true,
    checkedInAt: '2026-09-19T11:05:00',
    registeredAt: '2026-09-14T16:00:00',
    avatarColor: AVATAR_COLORS[5],
    projectInterests: ['Climate Tech', 'AI Assistants'],
    availability: 'Full weekend',
    matchScore: 86,
    bio: 'ML engineer passionate about climate. Looking for frontend partner.',
  },
  {
    id: 'p15',
    regId: 'ES26-0015',
    name: 'Dhruv Malhotra',
    email: 'dhruv.malhotra@nit.edu',
    college: 'NIT Trichy',
    skills: ['Go', 'Rust', 'PostgreSQL', 'Docker'],
    role: 'Backend',
    teamStatus: 'solo',
    teamId: null,
    checkedIn: false,
    checkedInAt: null,
    registeredAt: '2026-09-15T17:00:00',
    avatarColor: AVATAR_COLORS[6],
    projectInterests: ['Developer Tools', 'Fintech'],
    availability: 'Full weekend',
    matchScore: 83,
    bio: 'Backend specialist. Open to joining an existing team.',
  },
];

export const initialTeams: Team[] = [
  {
    id: 't1',
    name: 'Null Pointers',
    projectId: 'pr1',
    memberIds: ['p1', 'p2'],
    captainId: 'p1',
    formedAt: '2026-09-16T18:00:00',
  },
  {
    id: 't2',
    name: 'Gradient Descent',
    projectId: 'pr2',
    memberIds: ['p3', 'p4'],
    captainId: 'p3',
    formedAt: '2026-09-16T19:00:00',
  },
  {
    id: 't3',
    name: 'BlockChain Gang',
    projectId: 'pr3',
    memberIds: ['p5', 'p6'],
    captainId: 'p5',
    formedAt: '2026-09-17T10:00:00',
  },
  {
    id: 't4',
    name: 'Cloud Native',
    projectId: 'pr4',
    memberIds: ['p7', 'p8'],
    captainId: 'p7',
    formedAt: '2026-09-17T11:00:00',
  },
  {
    id: 't5',
    name: 'Synapse',
    projectId: 'pr5',
    memberIds: ['p9', 'p10'],
    captainId: 'p9',
    formedAt: '2026-09-17T12:00:00',
  },
  {
    id: 't6',
    name: 'The Overflow',
    projectId: 'pr6',
    memberIds: [],
    captainId: '',
    formedAt: '2026-09-18T09:00:00',
  },
];

export const initialProjects: Project[] = [
  {
    id: 'pr1',
    title: 'PulseBoard',
    category: 'Developer Tools',
    description:
      'A realtime collaborative dashboard for monitoring hackathon project health — builds, tests, and team mood in one glance.',
    teamId: 't1',
    status: 'submitted',
    submittedAt: '2026-09-21T14:30:00',
    repoUrl: 'github.com/nullpointers/pulseboard',
    demoUrl: 'pulseboard.demo',
  },
  {
    id: 'pr2',
    title: 'MediMind AI',
    category: 'AI/ML',
    description:
      'An on-device triage assistant that helps community health workers prioritize symptoms in low-connectivity regions.',
    teamId: 't2',
    status: 'submitted',
    submittedAt: '2026-09-21T15:00:00',
    repoUrl: 'github.com/gradientdescent/medimind',
    demoUrl: 'medimind.demo',
  },
  {
    id: 'pr3',
    title: 'TrustLedger',
    category: 'Web3',
    description:
      'A transparent micro-grants protocol for student projects with on-chain milestone verification.',
    teamId: 't3',
    status: 'submitted',
    submittedAt: '2026-09-21T15:20:00',
    repoUrl: 'github.com/blockchaingang/trustledger',
    demoUrl: 'trustledger.demo',
  },
  {
    id: 'pr4',
    title: 'GreenOps',
    category: 'Sustainability',
    description:
      'A carbon-aware deployment scheduler that shifts workloads to regions with cleaner energy in real time.',
    teamId: 't4',
    status: 'submitted',
    submittedAt: '2026-09-21T15:45:00',
    repoUrl: 'github.com/cloudnative/greenops',
    demoUrl: 'greenops.demo',
  },
  {
    id: 'pr5',
    title: 'EduMate',
    category: 'EdTech',
    description:
      'An adaptive tutoring agent that generates personalized practice problems from a single textbook photo.',
    teamId: 't5',
    status: 'submitted',
    submittedAt: '2026-09-21T16:00:00',
    repoUrl: 'github.com/synapse/edumate',
    demoUrl: 'edumate.demo',
  },
  {
    id: 'pr6',
    title: 'CodeClash Arena',
    category: 'Developer Tools',
    description:
      'A live multiplayer coding duel platform with spectator mode and instant replay.',
    teamId: 't6',
    status: 'pending',
    submittedAt: null,
    repoUrl: 'github.com/theoverflow/codeclash',
    demoUrl: '',
  },
  {
    id: 'pr7',
    title: 'FinScope',
    category: 'FinTech',
    description:
      'A personal finance forecaster that models 5-year outcomes from spending habits using Monte Carlo simulation.',
    teamId: '',
    status: 'draft',
    submittedAt: null,
    repoUrl: '',
    demoUrl: '',
  },
  {
    id: 'pr8',
    title: 'VitaSync',
    category: 'HealthTech',
    description:
      'A wearable-data aggregator that flags early signs of burnout for students during exam season.',
    teamId: '',
    status: 'late',
    submittedAt: '2026-09-21T17:30:00',
    repoUrl: 'github.com/vitasync/app',
    demoUrl: 'vitasync.demo',
  },
];

export const initialAnnouncements: Announcement[] = [
  {
    id: 'a1',
    title: 'Hacking has officially begun!',
    message:
      'The 36-hour clock is ticking. Remember to commit early and often. Mentors are roaming the floor — flag them down with the yellow table flag.',
    time: '2026-09-19T09:30:00',
    priority: 'high',
    venue: 'Main Hall',
    organizer: 'EventSphere Operations',
  },
  {
    id: 'a2',
    title: 'Lunch — South Block Cafeteria',
    message: 'Lunch is now being served. Vegetarian and vegan options available. Please bring your lanyard.',
    time: '2026-09-19T13:00:00',
    priority: 'medium',
    venue: 'South Block Cafeteria',
    organizer: 'EventSphere Operations',
  },
  {
    id: 'a3',
    title: 'ML Workshop by Dr. Kulkarni',
    message:
      'Hands-on session on efficient on-device inference starts in 30 minutes in Auditorium 2. Limited to 80 seats.',
    time: '2026-09-19T15:30:00',
    priority: 'low',
    venue: 'Auditorium 2',
    organizer: 'ML Track',
  },
  {
    id: 'a4',
    title: 'Submission deadline reminder',
    message: 'Final submissions close at 4:00 PM Sunday. No extensions. Upload your demo video (max 3 min) alongside your repo.',
    time: '2026-09-20T20:00:00',
    priority: 'high',
    venue: 'All Venues',
    organizer: 'EventSphere Operations',
  },
  {
    id: 'a5',
    title: 'Judging starts at 4:30 PM',
    message:
      'Judges will begin evaluations at 4:30 PM. Have your 90-second pitch ready at your table. Keep demos offline-ready.',
    time: '2026-09-21T11:00:00',
    priority: 'high',
    venue: 'Main Hall',
    organizer: 'Judging Committee',
  },
];

export const initialJudges: Judge[] = [
  {
    id: 'j1',
    name: 'Dr. Anjali Kulkarni',
    expertise: ['AI/ML', 'HealthTech'],
    assignedProjectIds: ['pr1', 'pr2', 'pr5'],
    avatarColor: AVATAR_COLORS[2],
  },
  {
    id: 'j2',
    name: 'Rohan Desai',
    expertise: ['Web3', 'FinTech'],
    assignedProjectIds: ['pr3', 'pr6', 'pr8'],
    avatarColor: AVATAR_COLORS[4],
  },
  {
    id: 'j3',
    name: 'Sneha Mukherjee',
    expertise: ['Developer Tools', 'EdTech'],
    assignedProjectIds: ['pr1', 'pr4', 'pr5'],
    avatarColor: AVATAR_COLORS[1],
  },
];

export const initialEvaluations: Evaluation[] = [
  {
    id: 'e1',
    projectId: 'pr2',
    judgeId: 'j1',
    judgeName: 'Dr. Anjali Kulkarni',
    scores: { innovation: 22, technical: 23, impact: 18, ux: 13, presentation: 13 },
    feedback:
      'Strong on-device architecture. Triage prioritization is genuinely useful. Tighten the onboarding flow for first-time health workers.',
    total: 89,
    submittedAt: '2026-09-21T16:30:00',
  },
  {
    id: 'e2',
    projectId: 'pr1',
    judgeId: 'j3',
    judgeName: 'Sneha Mukherjee',
    scores: { innovation: 20, technical: 22, impact: 16, ux: 14, presentation: 12 },
    feedback: 'Polished realtime UX. The team-mood widget is a delightful touch. Could explore exportable reports.',
    total: 84,
    submittedAt: '2026-09-21T16:45:00',
  },
  {
    id: 'e3',
    projectId: 'pr3',
    judgeId: 'j2',
    judgeName: 'Rohan Desai',
    scores: { innovation: 21, technical: 21, impact: 15, ux: 12, presentation: 13 },
    feedback: 'Milestone verification is a clever primitive. Gas optimization needs work before production.',
    total: 82,
    submittedAt: '2026-09-21T17:00:00',
  },
  {
    id: 'e4',
    projectId: 'pr4',
    judgeId: 'j3',
    judgeName: 'Sneha Mukherjee',
    scores: { innovation: 19, technical: 23, impact: 19, ux: 13, presentation: 12 },
    feedback: 'Carbon-aware scheduling is timely and well-executed. Loved the live region dashboard.',
    total: 86,
    submittedAt: '2026-09-21T17:10:00',
  },
  {
    id: 'e5',
    projectId: 'pr5',
    judgeId: 'j1',
    judgeName: 'Dr. Anjali Kulkarni',
    scores: { innovation: 21, technical: 20, impact: 18, ux: 14, presentation: 14 },
    feedback: 'Adaptive problem generation from a photo is impressive. Accuracy holds up well on edge cases.',
    total: 87,
    submittedAt: '2026-09-21T17:20:00',
  },
];

export const initialTimeline: TimelineEvent[] = [
  { id: 'tl1', time: '09:00', title: 'Opening Ceremony', description: 'Kickoff and rules briefing', type: 'checkpoint', done: true },
  { id: 'tl2', time: '09:30', title: 'Hacking Begins', description: '36-hour clock starts', type: 'checkpoint', done: true },
  { id: 'tl3', time: '13:00', title: 'Lunch', description: 'South Block Cafeteria', type: 'meal', done: true },
  { id: 'tl4', time: '16:00', title: 'ML Workshop', description: 'Efficient on-device inference', type: 'talk', done: true },
  { id: 'tl5', time: '20:00', title: 'Dinner & Mixer', description: 'Pizza and team networking', type: 'social', done: false },
  { id: 'tl6', time: '09:00', title: 'Day 2 Kickoff', description: 'Mentor office hours open', type: 'checkpoint', done: false },
  { id: 'tl7', time: '16:00', title: 'Submission Deadline', description: 'Final uploads close', type: 'deadline', done: false },
  { id: 'tl8', time: '16:30', title: 'Judging Begins', description: '90-second pitches start', type: 'checkpoint', done: false },
];

export const initialCheckIns: CheckInRecord[] = [
  { id: 'c1', participantId: 'p3', participantName: 'Arjun Nair', regId: 'ES26-0003', college: 'VIT Vellore', time: '2026-09-19T09:05:00' },
  { id: 'c2', participantId: 'p1', participantName: 'Aarav Sharma', regId: 'ES26-0001', college: 'IIT Bombay', time: '2026-09-19T09:12:00' },
  { id: 'c3', participantId: 'p2', participantName: 'Diya Patel', regId: 'ES26-0002', college: 'BITS Pilani', time: '2026-09-19T09:20:00' },
  { id: 'c4', participantId: 'p4', participantName: 'Ishita Reddy', regId: 'ES26-0004', college: 'IIIT Hyderabad', time: '2026-09-19T09:30:00' },
  { id: 'c5', participantId: 'p5', participantName: 'Kabir Singh', regId: 'ES26-0005', college: 'IIT Delhi', time: '2026-09-19T09:45:00' },
];

export const ATTENDANCE_TREND = [
  { label: '9 AM', checkIns: 120, registrations: 180 },
  { label: '10 AM', checkIns: 340, registrations: 420 },
  { label: '11 AM', checkIns: 560, registrations: 640 },
  { label: '12 PM', checkIns: 720, registrations: 780 },
  { label: '1 PM', checkIns: 820, registrations: 860 },
  { label: '2 PM', checkIns: 900, registrations: 920 },
  { label: '3 PM', checkIns: 960, registrations: 980 },
  { label: '4 PM', checkIns: 986, registrations: 1000 },
];

export const ENGAGEMENT_TREND = [
  { label: 'Fri', value: 62 },
  { label: 'Sat', value: 88 },
  { label: 'Sun', value: 95 },
];
